# Generated by Django 3.0.5 on 2024-03-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0019_auto_20240323_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('Branch', 'Branch'), ('ME', 'ME'), ('CSE', 'CSE')], default='Branch', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='fee',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
