# Generated by Django 3.0.5 on 2024-03-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0022_auto_20240323_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherextra',
            name='salary',
            field=models.CharField(max_length=40),
        ),
    ]
