# Generated by Django 3.0.5 on 2024-03-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0025_auto_20240323_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='Department',
            field=models.CharField(choices=[('Branch', 'Branch'), ('ME', 'ME'), ('CSE', 'CSE')], default='Branch', max_length=10),
        ),
    ]
