# Generated by Django 3.0.5 on 2024-04-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0031_auto_20240401_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
