# Generated by Django 3.0.5 on 2024-04-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0037_auto_20240404_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
