# Generated by Django 3.0.5 on 2024-04-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0040_auto_20240405_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='period',
            field=models.CharField(choices=[('I (9:30-10:20)', 'I (9:30-10:20)'), ('II', 'II (10:20-11:10)'), ('III', 'III (11:10-12:00)'), ('IV', 'IV (12:00-12:40)'), ('', ' (12:40-1:30)'), ('VI', 'VI (1:30-2:20)'), ('VII', 'VII (2:20-3:10)'), ('VIII', 'VIII (3:10-4:00)')], max_length=20),
        ),
    ]
