# Generated by Django 3.0.5 on 2024-04-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0045_collegetimetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='collegeTimetable',
        ),
    ]
