# Generated by Django 3.0.5 on 2024-04-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0049_remove_attendance_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STRTimetable2',
        ),
    ]
