# Generated by Django 5.0.3 on 2024-03-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0016_auto_20240319_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ME', 'ME')], default='one', max_length=10),
        ),
    ]
