# Generated by Django 3.0.5 on 2024-03-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0017_alter_studentextra_cl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('Select', 'Select'), ('ME', 'ME'), ('CSE', 'CSE')], default='one', max_length=10),
        ),
    ]
