# Generated by Django 3.0.5 on 2024-03-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0021_auto_20240323_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherextra',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
