# Generated by Django 3.0.5 on 2024-03-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0023_auto_20240323_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherextra',
            old_name='salary',
            new_name='subjects',
        ),
    ]
