# Generated by Django 3.0.5 on 2024-03-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0026_teacherextra_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherextra',
            name='subjects',
            field=models.CharField(max_length=40),
        ),
    ]
