# Generated by Django 3.0.5 on 2024-04-02 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0033_messageteachrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageteachrs',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='college.TeacherExtra'),
        ),
        migrations.AlterField(
            model_name='messageteachrs',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='college.StudentExtra'),
        ),
    ]
