# Generated by Django 3.0.5 on 2024-04-04 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0036_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.TeacherExtra'),
        ),
    ]
