# Generated by Django 3.0.5 on 2024-04-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0038_auto_20240405_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='period',
            field=models.CharField(choices=[('I (9:30-10:20)', 'I (9:30-10:20)'), ('II (10:20-11:10)', 'II (10:20-11:10)'), ('III (11:10-12:00)', 'III (11:10-12:00)'), ('IV (12:00-12:40)', 'IV (12:00-12:40)'), ('V (12:40-1:30)', 'V (12:40-1:30)'), ('VI (1:30-2:20)', 'VI (1:30-2:20)'), ('VII (2:20-3:10)', 'VII (2:20-3:10)'), ('VIII (3:10-4:00)', 'VIII (3:10-4:00)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
