# Generated by Django 3.0.5 on 2024-04-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0043_auto_20240406_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimetableEntry',
        ),
    ]
