# Generated by Django 3.0.5 on 2024-04-11 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0047_strtimetable2'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.TeacherExtra'),
            preserve_default=False,
        ),
    ]
