# Generated by Django 3.0.5 on 2024-04-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0048_attendance_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
    ]
