# Generated by Django 3.0.5 on 2024-04-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0050_delete_strtimetable2'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
